"""
CLI Entrypoint for Synthetic Data Generation Pipeline.

This script orchestrates the complete Phase 1C pipeline:
1. Load and sample CUAD clauses
2. Generate synthetic risk assessments via Claude API
3. Filter for quality
4. Create human anchor set (30 examples for evaluation)
5. Split into train/validation/test sets

Usage:
    python scripts/generate_synthetic.py --api-key YOUR_KEY
    python scripts/generate_synthetic.py --api-key YOUR_KEY --resume
    python scripts/generate_synthetic.py --filter-only
    python scripts/generate_synthetic.py --api-key YOUR_KEY --dry-run

CRITICAL: Never commit your API key. Use environment variables or .env files.
"""

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from datetime import datetime
from collections import Counter
import random

# Add src to path so we can import our modules
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from data.synthetic_generator import SyntheticGenerator, sample_clauses
from data.quality_filter import filter_and_save

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv not installed, that's OK

try:
    from sklearn.model_selection import train_test_split
    from tqdm import tqdm
except ImportError:
    print("[ERROR] Missing dependencies. Install with:")
    print("  pip install scikit-learn tqdm")
    sys.exit(1)

CUAD_SAMPLES_PER_CATEGORY = {
    "termination": 200,      # Sample from 1,886 available
    "liability": 200,        # Sample from 1,367 available
    "ip": 200,               # Sample from 1,201 available
    "non_compete": 200,      # Sample from 941 available
    "governing_law": 200,    # Sample from 452 available (nearly half!)
}

# Synthetic generation for missing categories
# These are fully generated by Claude (both clause and risk assessment)
SYNTHETIC_GENERATION = {
    "confidentiality": 100,   # No CUAD data, must generate
    "indemnification": 100,   # No CUAD data, must generate
}

DIFFICULTY_LEVELS = ["simple", "moderate", "complex"]
RISK_TENDENCIES = ["low_risk", "moderate_risk", "high_risk", "critical_risk"]

def setup_logging(log_file: Path) -> logging.Logger:
    """
    Configure logging to both console and file.

    Why log to file? Generation takes 1-2 hours and produces 1,200+ API calls.
    If something fails, we need the full log to debug.

    Args:
        log_file: Path to log file

    Returns:
        Configured logger instance
    """
    log_file.parent.mkdir(parents=True, exist_ok=True)

    logger = logging.getLogger("synthetic_generation")
    logger.setLevel(logging.INFO)

    console = logging.StreamHandler()
    console.setLevel(logging.INFO)
    console.setFormatter(
        logging.Formatter("[%(levelname)s] %(message)s")
    )
    logger.addHandler(console)

    file_handler = logging.FileHandler(log_file, encoding='utf-8')
    file_handler.setLevel(logging.DEBUG)
    file_handler.setFormatter(
        logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")
    )
    logger.addHandler(file_handler)

    return logger

def load_progress(progress_file: Path) -> set:
    """
    Load progress from previous run to support resume.

    Why resume support? Generating 1,200 examples takes ~1-2 hours.
    If the script crashes at example 800, we don't want to regenerate 1-799.

    Args:
        progress_file: Path to progress tracking JSON

    Returns:
        Set of processed clause IDs (or empty set if no progress)
    """
    if not progress_file.exists():
        return set()

    with open(progress_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
        return set(data.get("processed", []))

def save_progress(progress_file: Path, processed: set):
    """
    Save progress to enable resume.

    Args:
        progress_file: Path to progress tracking JSON
        processed: Set of processed clause IDs
    """
    progress_file.parent.mkdir(parents=True, exist_ok=True)
    with open(progress_file, 'w', encoding='utf-8') as f:
        json.dump({
            "processed": list(processed),
            "last_updated": datetime.now().isoformat()
        }, f, indent=2)

def generate_synthetic_data(
    api_key: str,
    output_file: Path,
    progress_file: Path,
    cuad_clauses_file: Path,
    logger: logging.Logger,
    resume: bool = False,
    dry_run: bool = False
) -> dict:
    """
    Generate synthetic risk assessments for CUAD clauses + fully synthetic clauses.

    This is the main generation loop. It:
    1. Loads CUAD clauses
    2. Samples according to CUAD_SAMPLES_PER_CATEGORY
    3. Generates risk assessments via Claude API
    4. Also generates fully synthetic clauses for confidentiality + indemnification
    5. Saves progress every 50 examples

    Args:
        api_key: Anthropic API key
        output_file: Path to save raw generated JSONL
        progress_file: Path to progress tracking file
        cuad_clauses_file: Path to raw_clauses.jsonl from Phase 1B
        logger: Logger instance
        resume: If True, skip already-processed clauses
        dry_run: If True, only process 5 examples for testing

    Returns:
        Dict with generation statistics
    """
    logger.info("="*70)
    logger.info("PHASE 1: Synthetic Data Generation")
    logger.info("="*70)

    logger.info(f"Loading CUAD clauses from {cuad_clauses_file}")
    cuad_clauses = []
    with open(cuad_clauses_file, 'r', encoding='utf-8') as f:
        for line in f:
            cuad_clauses.append(json.loads(line))

    logger.info(f"Loaded {len(cuad_clauses)} CUAD clauses")

    if dry_run:
        logger.info("[DRY RUN] Sampling only 5 clauses (1 per category)")
        sampled = sample_clauses(
            cuad_clauses,
            {k: 1 for k in CUAD_SAMPLES_PER_CATEGORY.keys()}
        )
    else:
        logger.info("Sampling clauses...")
        sampled = sample_clauses(cuad_clauses, CUAD_SAMPLES_PER_CATEGORY)

    logger.info(f"Sampled {len(sampled)} CUAD clauses")

    processed = load_progress(progress_file) if resume else set()
    if processed:
        logger.info(f"Resuming from previous run ({len(processed)} already processed)")

    generator = SyntheticGenerator(api_key=api_key, logger=logger)

    output_file.parent.mkdir(parents=True, exist_ok=True)
    mode = 'a' if resume else 'w'

    logger.info(f"\nGenerating risk assessments for {len(sampled)} CUAD clauses...")

    with open(output_file, mode, encoding='utf-8') as f:
        for i, clause in enumerate(tqdm(sampled, desc="CUAD clauses")):
            # Create a unique ID for this clause (for resume tracking)
            clause_id = f"cuad_{clause['source_doc']}_{clause['clause_type']}_{i}"

            if clause_id in processed:
                continue  # Skip already processed

            # Generate
            example = generator.generate_cuad_based(clause)

            if example:
                f.write(json.dumps(example) + '\n')
                f.flush()  # Ensure it's written immediately
                processed.add(clause_id)

            # Save progress every 50 examples
            if (i + 1) % 50 == 0:
                save_progress(progress_file, processed)
                cost = generator.estimate_cost()
                logger.info(
                    f"  [{i+1}/{len(sampled)}] "
                    f"Success: {generator.stats['successful']}, "
                    f"Failed: {generator.stats['failed_api'] + generator.stats['failed_parse']}, "
                    f"Cost: ${cost['total_cost_usd']:.2f}"
                )

    if not dry_run:
        logger.info(f"\nGenerating fully synthetic clauses...")

        for clause_type, num_to_generate in SYNTHETIC_GENERATION.items():
            logger.info(f"  Generating {num_to_generate} {clause_type} clauses...")

            with open(output_file, 'a', encoding='utf-8') as f:
                for i in tqdm(range(num_to_generate), desc=f"Synthetic {clause_type}"):
                    clause_id = f"synthetic_{clause_type}_{i}"

                    if clause_id in processed:
                        continue

                    # Cycle through difficulty and risk levels for variety
                    difficulty = DIFFICULTY_LEVELS[i % len(DIFFICULTY_LEVELS)]
                    risk_tendency = RISK_TENDENCIES[i % len(RISK_TENDENCIES)]

                    example = generator.generate_synthetic_clause(
                        clause_type=clause_type,
                        difficulty=difficulty,
                        risk_tendency=risk_tendency
                    )

                    if example:
                        f.write(json.dumps(example) + '\n')
                        f.flush()
                        processed.add(clause_id)

                    # Save progress every 50
                    if (i + 1) % 50 == 0:
                        save_progress(progress_file, processed)

    save_progress(progress_file, processed)

    cost = generator.estimate_cost()
    return {
        "total_attempted": generator.stats["total_attempted"],
        "successful": generator.stats["successful"],
        "failed_api": generator.stats["failed_api"],
        "failed_parse": generator.stats["failed_parse"],
        "estimated_cost_usd": cost["total_cost_usd"]
    }

def select_human_anchors(
    examples: list[dict],
    num_anchors: int = 30,
    random_seed: int = 42
) -> tuple[list[dict], list[dict]]:
    """
    Select a diverse set of examples as human evaluation anchors.

    Why human anchors? We need a small set of examples that a human expert
    can manually evaluate to validate our automated metrics. These are held
    out from training to ensure they're truly "unseen".

    Selection criteria:
    - Cover all 7 clause types (at least 4 per type if possible)
    - Mix of risk levels (low, medium, high, critical)
    - Mix of confidence levels
    - Diverse sources (CUAD vs synthetic)

    Args:
        examples: All filtered examples
        num_anchors: Number to select (default 30)
        random_seed: Random seed for reproducibility

    Returns:
        (anchors, remaining) tuple of example lists
    """
    random.seed(random_seed)

    by_type = {}
    for ex in examples:
        ct = ex["output"]["clause_type"]
        if ct not in by_type:
            by_type[ct] = []
        by_type[ct].append(ex)

    # Try to get ~4-5 per category (30 / 7 ≈ 4.3)
    target_per_type = max(4, num_anchors // len(by_type))

    anchors = []
    remaining_by_type = {}

    for clause_type, type_examples in by_type.items():
        # Shuffle for randomness
        random.shuffle(type_examples)

        # Take target_per_type examples
        num_to_take = min(target_per_type, len(type_examples))
        anchors.extend(type_examples[:num_to_take])
        remaining_by_type[clause_type] = type_examples[num_to_take:]

    # If we haven't reached num_anchors, sample more from largest categories
    if len(anchors) < num_anchors:
        needed = num_anchors - len(anchors)
        pool = []
        for remaining in remaining_by_type.values():
            pool.extend(remaining)
        random.shuffle(pool)
        anchors.extend(pool[:needed])
        # Remove these from remaining
        anchor_set = set(id(a) for a in anchors)
        pool = [ex for ex in pool if id(ex) not in anchor_set]
        remaining_by_type = {"mixed": pool}

    # Flatten remaining
    remaining = []
    for remaining_list in remaining_by_type.values():
        remaining.extend(remaining_list)

    return anchors[:num_anchors], remaining

def split_train_val_test(
    examples: list[dict],
    val_ratio: float = 0.1,
    test_ratio: float = 0.1,
    random_seed: int = 42
) -> tuple[list[dict], list[dict], list[dict]]:
    """
    Split examples into train/validation/test sets with stratification.

    Why stratified splitting? We want each split to have the same proportion
    of clause types. If all "governing_law" examples end up in test, the model
    won't learn them.

    Args:
        examples: Examples to split (after removing anchors)
        val_ratio: Fraction for validation (default 0.1 = 10%)
        test_ratio: Fraction for test (default 0.1 = 10%)
        random_seed: Random seed for reproducibility

    Returns:
        (train, val, test) tuple of example lists
    """
    # Extract labels for stratification
    labels = [ex["output"]["clause_type"] for ex in examples]

    # First split: separate test set
    train_val, test, train_val_labels, _ = train_test_split(
        examples,
        labels,
        test_size=test_ratio,
        stratify=labels,
        random_state=random_seed
    )

    # Second split: separate validation from train
    # Adjust val_ratio to account for already-split test set
    adjusted_val_ratio = val_ratio / (1 - test_ratio)

    train, val, _, _ = train_test_split(
        train_val,
        train_val_labels,
        test_size=adjusted_val_ratio,
        stratify=train_val_labels,
        random_state=random_seed
    )

    return train, val, test

def save_split(examples: list[dict], output_file: Path):
    """Save a list of examples to JSONL."""
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        for example in examples:
            f.write(json.dumps(example) + '\n')

def print_distribution(examples: list[dict], split_name: str):
    """Print the distribution of clause types in a split."""
    distribution = Counter(ex["output"]["clause_type"] for ex in examples)
    total = len(examples)

    print(f"\n[DISTRIBUTION - {split_name}]")
    for clause_type, count in distribution.most_common():
        pct = (count / total) * 100
        print(f"  {clause_type:20s} {count:4d} ({pct:5.1f}%)")

def main():
    parser = argparse.ArgumentParser(
        description="Generate synthetic risk assessment data for LegalRisk-LLM",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Full generation (requires API key)
  python scripts/generate_synthetic.py --api-key sk-ant-...

  # Resume from previous run
  python scripts/generate_synthetic.py --api-key sk-ant-... --resume

  # Dry run (5 examples only, ~$0.01)
  python scripts/generate_synthetic.py --api-key sk-ant-... --dry-run

  # Just run quality filter on existing data
  python scripts/generate_synthetic.py --filter-only
        """
    )

    parser.add_argument(
        "--api-key",
        help="Anthropic API key (or set ANTHROPIC_API_KEY env var)"
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume from previous run using progress file"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only process 5 examples for testing (~$0.01)"
    )
    parser.add_argument(
        "--filter-only",
        action="store_true",
        help="Skip generation, only run quality filter on existing data"
    )

    args = parser.parse_args()

    project_root = Path(__file__).parent.parent
    data_dir = project_root / "data"
    synthetic_dir = data_dir / "synthetic"

    cuad_clauses_file = data_dir / "raw_clauses.jsonl"
    raw_generated_file = synthetic_dir / "raw_generated.jsonl"
    filtered_file = synthetic_dir / "filtered.jsonl"
    filter_report_file = synthetic_dir / "filter_report.json"
    progress_file = synthetic_dir / "generation_progress.json"
    log_file = synthetic_dir / "generation.log"

    anchor_file = data_dir / "human_anchor_30.jsonl"
    train_file = synthetic_dir / "train.jsonl"
    val_file = synthetic_dir / "val.jsonl"
    test_file = synthetic_dir / "test.jsonl"

    logger = setup_logging(log_file)

    logger.info("="*70)
    logger.info("SYNTHETIC DATA GENERATION PIPELINE - PHASE 1C")
    logger.info("="*70)

    api_key = args.api_key or os.environ.get("ANTHROPIC_API_KEY")

    if not args.filter_only:
        if not api_key:
            logger.error("API key required. Provide via --api-key or ANTHROPIC_API_KEY env var")
            sys.exit(1)

        if not cuad_clauses_file.exists():
            logger.error(f"CUAD clauses file not found: {cuad_clauses_file}")
            logger.error("Run Phase 1B (cuad_processor.py) first")
            sys.exit(1)

        gen_stats = generate_synthetic_data(
            api_key=api_key,
            output_file=raw_generated_file,
            progress_file=progress_file,
            cuad_clauses_file=cuad_clauses_file,
            logger=logger,
            resume=args.resume,
            dry_run=args.dry_run
        )

        logger.info("\n" + "="*70)
        logger.info("GENERATION COMPLETE")
        logger.info("="*70)
        logger.info(f"Total attempted:  {gen_stats['total_attempted']:,}")
        logger.info(f"Successful:       {gen_stats['successful']:,}")
        logger.info(f"Failed (API):     {gen_stats['failed_api']:,}")
        logger.info(f"Failed (parse):   {gen_stats['failed_parse']:,}")
        logger.info(f"Estimated cost:   ${gen_stats['estimated_cost_usd']:.2f}")

        if args.dry_run:
            logger.info("\n[DRY RUN] Stopping here. Check output:")
            logger.info(f"  {raw_generated_file}")
            sys.exit(0)

    logger.info("\n" + "="*70)
    logger.info("PHASE 2: Quality Filtering")
    logger.info("="*70)

    if not raw_generated_file.exists():
        logger.error(f"Raw generated file not found: {raw_generated_file}")
        logger.error("Run generation first (without --filter-only)")
        sys.exit(1)

    filter_report = filter_and_save(
        input_path=raw_generated_file,
        output_path=filtered_file,
        report_path=filter_report_file,
        logger=logger
    )

    logger.info("\n" + "="*70)
    logger.info("FILTERING COMPLETE")
    logger.info("="*70)
    logger.info(f"Input to filter:     {filter_report['total_input']:,}")
    logger.info(f"Stage 1 removed:     {filter_report['stage_1_removed']:,}")
    logger.info(f"Stage 2 removed:     {filter_report['stage_2_removed']:,}")
    logger.info(f"Stage 3 removed:     {filter_report['stage_3_removed']:,}")
    logger.info(f"Stage 4 removed:     {filter_report['stage_4_removed']:,}")
    logger.info(f"Stage 5 removed:     {filter_report['stage_5_removed']:,}")
    logger.info(f"Passed all stages:   {filter_report['total_passed']:,}")
    logger.info(f"Pass rate:           {filter_report['pass_rate']:.1%}")

    filtered_examples = []
    with open(filtered_file, 'r', encoding='utf-8') as f:
        for line in f:
            filtered_examples.append(json.loads(line))

    logger.info("\n" + "="*70)
    logger.info("PHASE 3: Human Anchor Selection")
    logger.info("="*70)

    anchors, remaining = select_human_anchors(filtered_examples, num_anchors=30)

    logger.info(f"Selected {len(anchors)} human anchor examples")
    save_split(anchors, anchor_file)
    logger.info(f"Saved to {anchor_file}")

    logger.info("\n" + "="*70)
    logger.info("PHASE 4: Train/Val/Test Split")
    logger.info("="*70)

    train, val, test = split_train_val_test(remaining)

    logger.info(f"Train:      {len(train):,} examples")
    logger.info(f"Validation: {len(val):,} examples")
    logger.info(f"Test:       {len(test):,} examples")

    save_split(train, train_file)
    save_split(val, val_file)
    save_split(test, test_file)

    logger.info(f"\nSaved to:")
    logger.info(f"  {train_file}")
    logger.info(f"  {val_file}")
    logger.info(f"  {test_file}")

    print("\n" + "="*70)
    print("[SUCCESS] Synthetic Data Generation Complete")
    print("="*70)

    if not args.filter_only:
        print("[GENERATION]")
        print(f"  Total attempted:     {gen_stats['total_attempted']:,}")
        print(f"  Successful:          {gen_stats['successful']:,}")
        print(f"  Failed (API):        {gen_stats['failed_api']:,}")
        print(f"  Failed (parse):      {gen_stats['failed_parse']:,}")

    print("\n[FILTERING]")
    print(f"  Input to filter:     {filter_report['total_input']:,}")
    print(f"  Passed all stages:   {filter_report['total_passed']:,}")
    print(f"  Pass rate:           {filter_report['pass_rate']:.1%}")

    print("\n[SPLITS]")
    print(f"  Human anchor:        {len(anchors):,}")
    print(f"  Train:               {len(train):,}")
    print(f"  Validation:          {len(val):,}")
    print(f"  Test:                {len(test):,}")

    print_distribution(train, "Train Set")
    print_distribution(val, "Validation Set")
    print_distribution(test, "Test Set")

    if not args.filter_only:
        print(f"\n[COST]")
        print(f"  Estimated API cost:  ${gen_stats['estimated_cost_usd']:.2f}")

    print(f"\n[OUTPUT FILES]")
    if not args.filter_only:
        print(f"  {raw_generated_file}")
    print(f"  {filtered_file}")
    print(f"  {filter_report_file}")
    print(f"  {anchor_file}")
    print(f"  {train_file}")
    print(f"  {val_file}")
    print(f"  {test_file}")
    print("="*70 + "\n")

if __name__ == "__main__":
    main()
